// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyBudgetAppAPI.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MyBudgetAppAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260113204754_UseIdentityAlways")]
    partial class UseIdentityAlways
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MyBudgetAppAPI.Models.Transaction", b =>
                {
                    b.Property<int>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("TransactionId"));

                    b.Property<string>("Account")
                        .HasColumnType("text");

                    b.Property<double>("Amount")
                        .HasColumnType("double precision");

                    b.Property<string>("Category")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.Property<DateOnly>("TransactionDate")
                        .HasColumnType("date");

                    b.Property<string>("TransactionType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("TransactionId");

                    b.ToTable("Transactions");

                    b.HasData(
                        new
                        {
                            TransactionId = 1,
                            Account = "MainAccount",
                            Amount = 100.0,
                            Category = "Rent",
                            TransactionDate = new DateOnly(2026, 1, 13),
                            TransactionType = "Debit"
                        },
                        new
                        {
                            TransactionId = 2,
                            Account = "MainAccount",
                            Amount = 20.0,
                            Category = "Gas",
                            TransactionDate = new DateOnly(2026, 1, 13),
                            TransactionType = "Debit"
                        },
                        new
                        {
                            TransactionId = 3,
                            Account = "MainAccount",
                            Amount = 1000.0,
                            Category = "Salary",
                            TransactionDate = new DateOnly(2026, 1, 13),
                            TransactionType = "Credit"
                        },
                        new
                        {
                            TransactionId = 4,
                            Account = "MainAccount",
                            Amount = 60.0,
                            Category = "Groceries",
                            TransactionDate = new DateOnly(2026, 1, 13),
                            TransactionType = "Debit"
                        },
                        new
                        {
                            TransactionId = 5,
                            Account = "MainAccount",
                            Amount = 30.0,
                            Category = "Food",
                            TransactionDate = new DateOnly(2026, 1, 13),
                            TransactionType = "Debit"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
